// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"gorm.io/gorm"
	"todo_app/cli"
	"todo_app/cli/create_todo_command"
	"todo_app/cli/delete_todo_command"
	"todo_app/cli/get_todo_command"
	"todo_app/cli/list_todos_command"
	"todo_app/cli/make_todo_important_command"
	"todo_app/cli/make_todo_not_important_command"
	"todo_app/cli/update_todo_command"
	"todo_app/config"
	"todo_app/logger"
	"todo_app/logger/console_logger"
	"todo_app/logger/loggers"
	"todo_app/logger/zap_logger"
	"todo_app/repositories/to_do_repository"
	"todo_app/services/to_do_service"
	"todo_app/utils/gorm_util"
	"todo_app/utils/sql_util"
	"todo_app/utils/zap_util"
)

// Injectors from wire.go:

func InitGormWithMySQLDriver(dbConf *config.DBConfig) (*gorm.DB, func(), error) {
	db, cleanup, err := provideSQLDB(dbConf)
	if err != nil {
		return nil, nil, err
	}
	gormDB, err := gorm_util.NewSilentGormInstanceWithMySQLDriver(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return gormDB, func() {
		cleanup()
	}, nil
}

func InitTodoService(gormDB *gorm.DB) to_do_service.ITODOService {
	todoRepository := to_do_repository.New(gormDB)
	todoService := to_do_service.New(todoRepository)
	return todoService
}

func InitCompositeLoggerWithZapAndConsole(loggerConf *config.LoggerConfig) (logger.ILogger, error) {
	zapLogger, err := zap_util.NewZapLogger(loggerConf)
	if err != nil {
		return nil, err
	}
	zap_loggerZapLogger := zap_logger.New(zapLogger)
	consoleLoggerParams := _wireConsoleLoggerParamsValue
	consoleLogger := console_logger.New(consoleLoggerParams)
	iLogger := provideLoggersWithZapAndConsoleLogger(zap_loggerZapLogger, consoleLogger)
	return iLogger, nil
}

var (
	_wireConsoleLoggerParamsValue = &console_logger.ConsoleLoggerParams{MethodNamespaceSkip: 3}
)

func InitCLICommands(todoService to_do_service.ITODOService, logger2 logger.ILogger) *cli.RootCommand {
	v := provideCLICommands(todoService, logger2)
	rootCommand := cli.NewRootCommand(v)
	return rootCommand
}

// wire.go:

func provideSQLDB(dbConf *config.DBConfig) (*sql.DB, func(), error) {
	sqlDB, err := sql_util.CreateConnection(dbConf)
	if err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		err := sql_util.CloseConnection(sqlDB)
		if err != nil {
			panic(err)
		}
	}

	return sqlDB, cleanup, nil
}

func provideLoggersWithZapAndConsoleLogger(
	zapLogger *zap_logger.ZapLogger,
	consoleLogger *console_logger.ConsoleLogger,
) logger.ILogger {
	return loggers.New(zapLogger, consoleLogger)
}

func provideCLICommands(todoService to_do_service.ITODOService, logger2 logger.ILogger) []cli.ICommand {
	createToDoCmd := create_todo_command.New(todoService, logger2)
	deleteToDoCmd := delete_todo_command.New(todoService, logger2)
	getToDoCmd := get_todo_command.New(todoService, logger2)
	listToDoCmd := list_todos_command.New(todoService, logger2)
	updatedToDoCmd := update_todo_command.New(todoService, logger2)
	makeToDoImportantCmd := make_todo_important_command.New(todoService, logger2)
	makeToDoNotImportantCmd := make_todo_not_important_command.New(todoService, logger2)
	cliCommands := []cli.ICommand{
		createToDoCmd,
		deleteToDoCmd,
		getToDoCmd,
		listToDoCmd,
		updatedToDoCmd,
		makeToDoImportantCmd,
		makeToDoNotImportantCmd,
	}

	return cliCommands
}
